server:
  port: 5000

spring:
  application:
    name: auditech-demo
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/auditech_demo
    username: root
    password: ${SQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver


connection-request-timeout: 5000
read-timeout: 5000